services:
    db:
        image: postgres:latest
        container_name: Proyecto3Dverse
        restart: always
        environment:
            POSTGRES_USER: ruben
            POSTGRES_PASSWORD: "1234"
            POSTGRES_DB: Proyecto3Dverse
        ports:
            - "54876:5432"
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
    postgres_data:
